# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create dot env file
        uses: actions/setup-node@v1
      - shell: bash
        run: |
          touch .env
          echo 'VUE_APP_KUROMOJI_DICT="https://kikuchiken-waseda.github.io/mri-vuewer.ver2/dict/"' >> .env
          echo 'VUE_APP_DROPBOX_REDIRECT="/mri-vuewer.ver2/dict/"' >> .env
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.1"
      - name: Install dependencies
        run: yarn
      - name: CI
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
