# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.1"
      - name: Install dependencies
        run: yarn
      - name: Run a one-line script
        run: ls
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
