name: CI

on:
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create dot env file
        uses: actions/setup-node@v1
      - shell: bash
        run: |
          touch .env
          echo 'VUE_APP_KUROMOJI_DICT="/mri-vuewer.ver2/dict/"' >> .env
          echo 'VUE_APP_DROPBOX_REDIRECT="https://kikuchiken-waseda.github.io/mri-vuewer.ver2"' >> .env
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: Install dependencies
        run: yarn
      - name: test
        run: |
          yarn lint
          yarn test:unit
